[simulation]
    name = "alegria" # name of the simulation. If None or "", default name is used.
    start_datetime = 2022-04-13T08:41:00 # start date of the simulation
    sim_length = 96.0 # length of the simulation in HOURS
    time_step = 1800 # simulation time step in SECONDS
    spill_lat = [33.661] # lat of oil spill
    spill_lon = [32.697] # lon of oil spill
    spill_duration = [0.0] # duration of oil spill HOURS. = 0 for instantaneous release
    spill_rate = [100.5] # spill rate TONS/HOUR
    slick_age = [0.0] # age of oil slick in HOURS
    oil = [28] #either api of the oil or name, considering that name must be exact
    multiple_slick = false
    advanced_parameters = false # user must provide config2.txt 
[download]
    download_data = true
    download_curr = true
    download_wind = true
    copernicus_user = 'iruizatake'
    copernicus_password = 'Hamburguer1!'
    ecmwf_api = 'None'
[input_files]
    preproc_path = "cases/" # where preprocessed MET/OCE data should be placed
    set_domain = false
    delta = [2.0] #default distance in degrees to download or crop data in case lat and lon areas are not provided 
    lat = [39, 41]
    lon = [17, 19.5]
    [input_files.dtm]
        bathymetry_path = "data/gebco/GEBCO_2023.nc" # GEBCO 2023 bathymetry file
        coastline_path = "data/gshhs/f/GSHHS_f_L1.shp" # coastline shapefile gshhs
[run_options]
    preprocessing = true
    preprocessing_metoce = true
    preprocessing_dtm = true
    run_model = true
    postprocessing = true # conversion from particles to concentration
[plot_options]
    plotting = true
    # Domain for plotting [min lon, max lon, min lat, max lat]
    define_boundaries = false
    plot_lon = [-64.1,-63.5]
    plot_lat = [10.6,11]