[simulation]
    name = "paria" # name of the simulation.
    experiment_path = "cases/" # path where experiment folder should be placed
    start_datetime = 2017-04-24T13:00:00 # start date of the simulation
    sim_length = 48.0 # length of the simulation in HOURS
    spill_lat = [10.8107] # lat of oil spill
    spill_lon = [-63.5497] # lon of oil spill
    spill_duration = [120.0] # duration of oil spill HOURS. = 0 for instantaneous release
    spill_rate = [1.5] # spill rate TONS/HOUR
    slick_age = [0.0] # age of oil slick in HOURS
    oil = ["Sylvestre"] # either api (number) of the oil or name (string), e.g. ["Ragusa"]. considering that name must be exact
    area_spill = false
    area_vertex = [] #comprehends thre levels of lists. 1st: all slicks. 2nd: individual slick. 3rd: Coordinates of each vertex in each individual slick
    multiple_slick = false
    advanced_parameters = true # user must provide parameters.toml file
    advanced_parameters_path = "cases/paria/parameters_paria.toml" # this path shuld be provided only if "advanced_parameters" is = true
[download]
    download_data = false
    download_curr = false
    download_wind = false
    copernicus_user = 'username'
    copernicus_password = 'None'
[input_files]
    set_domain = false
    delta = [0.75] # default distance in degrees to download or crop data in case lat and lon areas are not provided
    lat = []
    lon = []
    [input_files.dtm]
        bathymetry_path = "none" # GEBCO 2023 bathymetry file
        coastline_path = "none" # coastline shapefile gshhs
    [input_files.metoce]
        oce_data_path = "cases/paria/oce_files"
        met_data_path = "cases/paria/met_files"
    [input_files.shapefile]
        shape_path = "none"
[run_options]
    preprocessing = false
    preprocessing_metoce = false
    preprocessing_dtm = false
    run_model = true
    postprocessing = true # conversion from particles to concentration
[plot_options]
    plotting = true
    # Domain for plotting
    plot_lon = [-64.1,-63.5] # [min lon, max lon]
    plot_lat = [10.6,11] # [min lat, max lat]]
