[simulation]
    name = "algeria" # name of the simulation.
    experiment_path = "cases/" # path where experiment folder should be placed
    start_datetime = 2008-08-06T10:00:00 # start date of the simulation
    sim_length = 36.0 # length of the simulation in HOURS
    spill_lat = [38.28] # lat of oil spill
    spill_lon = [5.5] # lon of oil spill
    spill_duration = [0.0] # duration of oil spill HOURS. = 0 for instantaneous release
    spill_rate = [240.0] # spill rate TONS/HOUR
    slick_age = [0.0] # age of oil slick in HOURS
    oil = [22.40] # either api (number) of the oil or name (string), e.g. ["Ragusa"]. considering that name must be exact
    area_spill = true
    area_vertex = [[[38.2750,5.2645],[38.2942,5.5491],[38.2712,5.8559],[38.2994,5.5434]],
                   [[38.2568,5.9367],[38.2022,6.0566],[38.1585,6.2115],[38.2175,6.0423]],
                   [[38.1192,6.3190],[38.1341,6.3090],[38.1001,6.4237],[38.0886,6.4194]]
                    ] #lat and lon lists for each one of the vertex
    multiple_slick = false
    advanced_parameters = true # user must provide parameters.toml file
    advanced_parameters_path = "cases/algeria/parameters_algeria.toml" # this path shuld be provided only if "advanced_parameters" is = true
[download]
    download_data = false
    download_curr = false
    download_wind = false
    copernicus_user = 'username'
    copernicus_password = 'None'
[input_files]
    set_domain = true
    delta = [0.75] # default distance in degrees to download or crop data in case lat and lon areas are not provided
    lat = [37.5,38.5]
    lon = [4.5,7.5]
    [input_files.dtm]
        bathymetry_path = "data/gebco/GEBCO_2023.nc" # GEBCO 2023 bathymetry file
        coastline_path = "data/gshhs/f/GSHHS_f_L1.shp" # coastline shapefile gshhs
    [input_files.metoce]
        oce_data_path = "cases/algeria/input_data/oce"
        met_data_path = "cases/algeria/input_data/met"
    [input_files.shapefile]
        shape_path = false
[run_options]
    preprocessing = true
    preprocessing_metoce = true
    preprocessing_dtm = true
    run_model = true
    postprocessing = true # conversion from particles to concentration
[plot_options]
    plotting = true
    # Domain for plotting
    plot_lon = [4.5,7.5]
    plot_lat = [37.5,38.5]
