[simulation]
    name = "algeria" # name of the simulation. If None or "", default name is used.
    start_datetime = 2008-08-06T10:00:00 # start date of the simulation
    sim_length = 36.0 # length of the simulation in HOURS
    time_step = 1800 # simulation time step in SECONDS
    spill_lat = [38.28] # lat of oil spill
    spill_lon = [5.5] # lon of oil spill
    spill_duration = [0.0] # duration of oil spill HOURS. = 0 for instantaneous release
    spill_rate = [240.0] # spill rate TONS/HOUR
    slick_age = [0.0] # age of oil slick in HOURS
    oil = [28] #either api of the oil or name, considering that name must be exact
    multiple_slick = true
    advanced_parameters = true # user must provide config2.txt 
[download]
    download_data = true
    download_curr = true
    download_wind = true
    copernicus_user = 'jramos7'
    copernicus_password = 'Hamstervoador1'
    ecmwf_api = 'None'
[input_files]
    preproc_path = "cases/" # where preprocessed MET/OCE data should be placed
    set_domain = false
    delta = [0.75] #default distance in degrees to download or crop data in case lat and lon areas are not provided 
    lat = [39, 41]
    lon = [17, 19.5]
    [input_files.dtm]
        bathymetry_path = "data/gebco/GEBCO_2024_sub_ice_topo.nc" # GEBCO 2024 bathymetry file
        coastline_path = "data/gshhs/GSHHS_f_L1.shp" # coastline shapefile gshhs
[run_options]
    preprocessing = true
    preprocessing_metoce = true
    preprocessing_dtm = true
    run_model = true
    postprocessing = true # conversion from particles to concentration
[plot_options]
    plotting = true
    # Domain for plotting [min lon, max lon, min lat, max lat]
    define_boundaries = true
    plot_lon = [5.25,7]
    plot_lat = [38,38.5]