[simulation]
    name = "syria" # name of the simulation.
    experiment_path = "cases/" # path where experiment folder should be placed
    start_datetime = 2021-08-22T13:43:00 # start date of the simulation
    sim_length = 24.0 # length of the simulation in HOURS
    spill_lat = [35.25] # lat of oil spill
    spill_lon = [35.90] # lon of oil spill
    spill_duration = [0.0] # duration of oil spill HOURS. = 0 for instantaneous release
    spill_rate = [27.78] # spill rate TONS/HOUR
    slick_age = [0.0] # age of oil slick in HOURS
    oil = [28] # either api (number) of the oil or name (string), e.g. ["Ragusa"]. considering that name must be exact
    area_spill = true
    area_vertex = false #comprehends thre levels of lists. 1st: all slicks. 2nd: individual slick. 3rd: Coordinates of each vertex in each individual slick
    multiple_slick = false
    advanced_parameters = false # user must provide parameters.toml file
    advanced_parameters_path = "" # this path shuld be provided only if "advanced_parameters" is = true
[download]
    download_data = true
    download_curr = true
    download_wind = true
    copernicus_user = "user"
    copernicus_password = "password"
[input_files]
    set_domain = false
    delta = [0.75] # default distance in degrees to download or crop data in case lat and lon areas are not provided
    lat = [9, 12]
    lon = [-62, -65]
[input_files.dtm]
    bathymetry_path = "data/gebco/GEBCO_2024_sub_ice_topo.nc" # GEBCO 2024 bathymetry file
    coastline_path = "data/gshhs/GSHHS_f_L1.shp" # coastline shapefile gshhs
[input_files.metoce]
    oce_data_path = "path/to/oce/data"
    met_data_path = "path/to/met/data"
[input_files.shapefile]
    shape_path = "cases/syria/result.shp" # add "path/to/shapefile" in case you want to start from shapefile
[run_options]
    preprocessing = true
    preprocessing_metoce = true
    preprocessing_dtm = true
    run_model = true
    postprocessing = true # conversion from particles to concentration
[plot_options]
    plotting = true
    # Domain for plotting
    plot_lon = [35.75,36] # [min lon, max lon]
    plot_lat = [35.1,35.4] # [min lat, max lat]]
