[simulation]
    name = "lebanon" # name of the simulation.
    experiment_path = "cases/" # path where experiment folder should be placed
    start_datetime = 2006-07-13T08:00:00 # start date of the simulation
    sim_length = 240.0 # length of the simulation in HOURS
    spill_lat = [33.6833] # lat of oil spill
    spill_lon = [35.1667] # lon of oil spill
    spill_duration = [144.0] # duration of oil spill HOURS. = 0 for instantaneous release
    spill_rate = [130.35] # spill rate TONS/HOUR
    slick_age = [0.0] # age of oil slick in HOURS
    oil = [19.80] #either api of the oil or name, considering that name must be exact
    area_spill = false
    area_vertex = [[38.2750,5.2645],[38.2942,5.5491],[38.2712,5.8559],[38.2994,5.9376]] #lat and lon lists for each one of the vertex
    multiple_slick = false
    advanced_parameters = true # user must provide config2.txt
    advanced_parameters_path = "cases/lebanon/parameters_lebanon.toml" # this path shuld be provided only if "advanced_parameters" is = true 
[download]
    download_data = false
    download_curr = false
    download_wind = false
    copernicus_user = 'username'
    copernicus_password = 'None'
[input_files]
    set_domain = false
    delta = [0.75] #default distance in degrees to download or crop data in case lat and lon areas are not provided 
    lat = []
    lon = []
    [input_files.dtm]
        bathymetry_path = "none" # GEBCO 2023 bathymetry file
        coastline_path = "none" # coastline shapefile gshhs
    [input_files.metoce]
        oce_data_path = "cases/lebanon/oce_files"
        met_data_path = "cases/lebanon/met_files"
    [input_files.shapefile]
        shape_path = "none"
[run_options]
    preprocessing = false
    preprocessing_metoce = false
    preprocessing_dtm = false
    run_model = true
    postprocessing = true # conversion from particles to concentration
[plot_options]
    plotting = true
    # Domain for plotting [min lon, max lon, min lat, max lat]
    define_boundaries = true
    plot_lon = [34.75,35.75]
    plot_lat = [33.5,34.5]